apiVersion: apps/v1
kind: Deployment
namespace:  test-app  
metadata:
  name: nginx-app-deployment
spec:
  selector:
    matchLabels:
      app: nginx-app-deployment
  template:
    metadata:
      labels:
        app: nginx-app-deployment
    spec:
      containers:
      - name: nginx-app-deployment
        image: node/server:1.0 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        # - containerPort: <Port>
  