apiVersion: apps/v1
kind: Deployment  
metadata:
  name: nginx-app-deployment-standalone 
  namespace:  test-app 
spec:
  replicas : 2 
  selector:
    matchLabels:
      app: nginx-app-deployment-standalone
  template:
    metadata:
      labels:
        app: nginx-app-deployment-standalone
    spec:
        
      containers:
      - name: nginx-app-deployment
        image: node/server:1.0 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        # - containerPort: <Port>
  