# kubectl expose deployment nginx-app-deployment --type=NodePort --port=8060 -n test-app   
# issue at node port : the service should work either with localhost:{{NodePort}} or {{NodeIP}}:{{NodePort}}    
apiVersion: v1
kind: Service  
metadata:
  name: nginx-app-node-np 
  namespace:  test-app
spec:
  type: NodePort   
  selector:
    app: nginx-app-deployment 
  ports:
    - 
      port: 8060
      targetPort: 8080
      nodePort: 31100  
