apiVersion: v1
kind: Pod
metadata:
  name: my-nginx1-emptydir
  labels:
        app: nginx-app-volumes   
spec:
  volumes:
    - name: html
      emptyDir: {}
  containers:
    - env:  
      - name: POD_IP
        valueFrom:  
          fieldRef:
            fieldPath: status.podIP
      
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $POD_IP >> /html/index.html; date >> /html/index.html;    sleep 10;done"]        
      name: html-updater      
      image: alpine
      volumeMounts:
        - name : html
          mountPath: /html

    - name: nginx 
      image: nginx:alpine
      volumeMounts:
        - name : html
          mountPath: /usr/share/nginx/html
          readOnly: true   