apiVersion: v1
kind: Pod
metadata:
  name: my-nginx1-env1
spec:
  containers:
    - env:  
      - name: POD_IP
        valueFrom:  
          fieldRef:
            fieldPath: status.podIP 
      name: nginx1-container
      image:  nginx:alpine
      livenessProbe:  
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds:  15
        timeoutSeconds: 2
        periodSeconds:  5
        failureThreshold: 1          



