apiVersion: v1
kind: Pod
metadata:
  name: my-nginx1-1
spec:
  containers:
    - name: nginx1-container
      image:  nginx:alpine
      livenessProbe:  
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds:  15
        timeoutSeconds: 2
        periodSeconds:  5
        failureThreshold: 1          



