apiVersion: v1
kind:   Pod
metadata:
  name: echo-busybox-prober 
spec: 
 containers:
    - name: probe-busybox-container 
      image:  k8s.gcr.io/busybox

      env:
        - name: MESSAGE
          value: "hello world" 
      command: ["sh"]    
      args:
        - -c
        - "while true; do echo $(MESSAGE); sleep 10; done;" 
      readinessProbe:
        httpGet:  
          path: /index.html
          port: 80     
        initialDelaySeconds:  15
        timeoutSeconds: 2
        periodSeconds:  5
        failureThreshold: 1  