apiVersion: v1
kind:   Pod
metadata:
  name: busybox-probe
spec: 
  containers:
    - name: busybox-container
      image:  k8s.gcr.io/busybox

      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 60;
          rm -rf /tmp/healthy; sleep 600;

      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds:  15
        timeoutSeconds: 2
        periodSeconds:  5
        failureThreshold: 1                     

